@tool
extends Object

## Swaps mesh materials based on nexus_material_id using material_index.json.
## Targets may be StandardMaterial3D, ORMMaterial3D, or ShaderMaterial (.tres + .gdshader from shader graph convert).

const EXPECTED_SHADER_CONVERT_VERSION := 5

var _material_index: Dictionary = {}
var _index_loaded: bool = false
var _warned_versions: Dictionary = {}

func _load_material_index() -> bool:
	var path = NexusPaths.material_index_path()
	var file = FileAccess.open(path, FileAccess.READ)
	if not file:
		_index_loaded = true
		return false

	var json = JSON.new()
	if json.parse(file.get_as_text()) == OK:
		_material_index = json.get_data()
	file.close()

	_index_loaded = true
	return not _material_index.is_empty()

func process(node: Node, stats: Dictionary) -> void:
	if not node is MeshInstance3D or not is_instance_valid(node.mesh): return
	if not _load_material_index(): return

	var mesh_was_duplicated = false
	var swapped_count = 0

	for i in range(node.mesh.get_surface_count()):
		var current_material: Material = node.mesh.surface_get_material(i)
		if not is_instance_valid(current_material): continue
			
		if current_material.has_meta("extras"):
			var extras = current_material.get_meta("extras")
			if extras.has("nexus_material_id"):
				var mat_id = extras["nexus_material_id"]
				var mat_entry = _material_index.get(mat_id, {})
				if mat_entry is Dictionary:
					var rel_path = mat_entry.get("relative_path", "")
					if not rel_path.is_empty():
						var tres_path = NexusUtils.validate_index_path(rel_path)
						if not tres_path.is_empty() and ResourceLoader.exists(tres_path):
							var external_material = ResourceLoader.load(tres_path, "", ResourceLoader.CACHE_MODE_REPLACE)
							if is_instance_valid(external_material):
								_check_shader_convert_version(external_material, mat_id)
								if not mesh_was_duplicated:
									node.mesh = node.mesh.duplicate()
									mesh_was_duplicated = true
								node.mesh.surface_set_material(i, external_material)
								if external_material.get_meta("nexus_uses_vertex_color", false):
									_ensure_mesh_vertex_colors(node)
								swapped_count += 1
	
	stats.materials += swapped_count


## Warns once per material when shader_convert version in metadata does not match the importer.
func _check_shader_convert_version(material: Material, mat_id: String) -> void:
	if material is not ShaderMaterial:
		return
	if _warned_versions.has(mat_id):
		return
	var version := 1
	if material.has_meta("nexus_shader_convert_version"):
		version = int(material.get_meta("nexus_shader_convert_version"))
	if version != EXPECTED_SHADER_CONVERT_VERSION:
		_warned_versions[mat_id] = true
		push_warning("[Nexus] Material '%s' was generated by shader_convert v%d (importer expects v%d). Re-export from Blender to refresh." % [mat_id, version, EXPECTED_SHADER_CONVERT_VERSION])


## Godot 4.4+ can import vertex colors but fail to bind them to spatial shader COLOR.
## Rebuild surfaces with explicit PackedColorArray when a converted shader reads them.
func _ensure_mesh_vertex_colors(node: MeshInstance3D) -> void:
	if not is_instance_valid(node.mesh) or node.mesh.get_surface_count() == 0:
		return

	var source_mesh: Mesh = node.mesh
	var new_mesh := ArrayMesh.new()
	var rebuilt := false

	for surface_idx in range(source_mesh.get_surface_count()):
		var arrays = source_mesh.surface_get_arrays(surface_idx)
		var colors = arrays[Mesh.ARRAY_COLOR]
		if colors != null and colors.size() > 0:
			var color_array := PackedColorArray()
			for color in colors:
				if color is Color:
					color_array.push_back(color)
				else:
					var alpha := 1.0
					if color.size() > 3:
						alpha = color[3]
					color_array.push_back(Color(color[0], color[1], color[2], alpha))
			arrays[Mesh.ARRAY_COLOR] = color_array
			rebuilt = true

		new_mesh.add_surface_from_arrays(
			source_mesh.surface_get_primitive_type(surface_idx),
			arrays,
		)
		new_mesh.surface_set_material(surface_idx, source_mesh.surface_get_material(surface_idx))

	if rebuilt:
		node.mesh = new_mesh
		print_verbose(" -> Rebuilt mesh vertex colors for shader COLOR on '%s'." % node.name)
